import type { StockAnalysis } from "@/types/stock";
import {
  streamStockAnalysis as mistralStockStream,
  streamGeneralChat as mistralGeneralStream,
  validateMistralSetup,
  friendlyMistralError,
  generateDailyBrief as mistralGenerateDailyBrief,
} from "./mistral";
import {
  streamStockAnalysis as groqStockStream,
  streamGeneralChat as groqGeneralStream,
  validateGroqSetup,
  friendlyGroqError,
  generateDailyBrief as groqGenerateDailyBrief,
} from "./groq";
// import {
//   streamStockAnalysis as geminiStockStream,
//   streamGeneralChat as geminiGeneralStream,
//   validateGeminiSetup,
//   friendlyGeminiError,
//   generateDailyBrief as geminiGenerateDailyBrief,
// } from "./gemini";

type ChatRole = "user" | "assistant";
type ChatHistory = Array<{ role: ChatRole; content: string }>;

export type ChatMode = "stock" | "general";

interface StreamChatArgs {
  mode: ChatMode;
  message: string;
  history: ChatHistory;
  analysis?: StockAnalysis;
  kind?: "brief" | "normal";
  model?: "mistral";
  userMemory?: string;
}

export function validateAiSetup(): {
  valid: boolean;
  error?: string;
  stockPrimary: "mistral" | "groq" | "none";
  generalPrimary: "groq" | "mistral" | "none";
  fallback: "groq" | "mistral" | "none";
} {
  const mistral = validateMistralSetup();
  const groq = validateGroqSetup();
  // const gemini = validateGeminiSetup();

  const stockPrimary = mistral.valid ? "mistral" : groq.valid ? "groq" : "none";
  const generalPrimary = groq.valid ? "groq" : mistral.valid ? "mistral" : "none";
  const fallback = groq.valid ? "groq" : mistral.valid ? "mistral" : "none";

  const valid = stockPrimary !== "none" && generalPrimary !== "none";

  if (!valid) {
    return {
      valid: false,
      stockPrimary: "none",
      generalPrimary: "none",
      fallback: "none",
      error: `No LLM configured. Mistral: ${mistral.error}, Groq: ${groq.error}`,
    };
  }

  return {
    valid: true,
    stockPrimary,
    generalPrimary,
    fallback,
  };
}

export async function streamChat(
  args: StreamChatArgs
): Promise<{ stream: ReadableStream<Uint8Array>; provider: string }> {
  const setup = validateAiSetup();
  if (!setup.valid) {
    throw new Error("No LLM provider is configured");
  }

  const providers = args.mode === "stock"
    ? [setup.stockPrimary, setup.fallback].filter(p => p !== "none")
    : [setup.generalPrimary, setup.fallback].filter(p => p !== "none");

  for (const provider of providers) {
    try {
      let stream: ReadableStream<Uint8Array>;
      if (args.mode === "stock") {
        if (!args.analysis) throw new Error("Stock mode requires analysis data");
        if (provider === "mistral") {
          stream = await mistralStockStream(
            args.message,
            args.analysis,
            args.history,
            args.userMemory
          );
        } else if (provider === "groq") {
          stream = await groqStockStream(
            args.message,
            args.analysis,
            args.history,
            args.userMemory
          );
        }
      } else {
        if (provider === "groq") {
          stream = await groqGeneralStream(
            args.message,
            args.history,
            args.kind ?? "normal",
            args.userMemory
          );
        } else if (provider === "mistral") {
          stream = await mistralGeneralStream(
            args.message,
            args.history,
            args.kind ?? "normal",
            args.userMemory
          );
        }
      }
      console.log(`[AI] Response generated by ${provider}`);
      return { stream, provider };
    } catch (err) {
      console.warn(`Provider ${provider} failed:`, err);
      continue;
    }
  }

  throw new Error("All LLM providers failed");
}

export async function generateDailyBrief(prompt: string): Promise<string> {
  const setup = validateAiSetup();
  if (!setup.valid) {
    return `Unable to generate brief. ${setup.error ?? "No AI provider configured."}`;
  }

  const providers = setup.primary === "mistral" ? ["mistral", "groq"] : ["groq", "mistral"];

  for (const provider of providers) {
    try {
      const text = provider === "mistral"
        ? await mistralGenerateDailyBrief(prompt)
        : await groqGenerateDailyBrief(prompt);
      if (text && !/^Unable to generate brief/i.test(text)) {
        return text;
      }
    } catch (err) {
      console.warn(`Daily brief provider ${provider} failed:`, err);
    }
  }

  return "Unable to generate brief right now.";
}

export async function classifyIntent(message: string): Promise<{
  intent: string;
  company_name: string | null;
  symbols: string[];
  query_type: string;
} | null> {
  const text = message.trim();
  if (!text) return null;

  if (/^(hi|hey|hello|yo|thanks|thank you|bye|ok|okay)$/i.test(text)) {
    return {
      intent: "greeting",
      company_name: null,
      symbols: [],
      query_type: "general",
    };
  }

  const tickerMatch = text.match(/\$?([A-Z]{1,10}(?:\.[A-Z]{1,2})?)\b/);
  if (tickerMatch) {
    return {
      intent: "stock_query",
      company_name: null,
      symbols: [tickerMatch[1].toUpperCase()],
      query_type: "analysis",
    };
  }

  if (/\b(analyze|analysis|stock|share|price|quote|buy|sell|target)\b/i.test(text)) {
    return {
      intent: "stock_query",
      company_name: text,
      symbols: [],
      query_type: "analysis",
    };
  }

  return {
    intent: "general_finance",
    company_name: null,
    symbols: [],
    query_type: "general",
  };
}
